# Site settings
title: "CipherSquad"
description: "Lazy ass puzzle enthusiasts with no constructive goals."
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "Cipher Squad"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
